"""
Provider Metadata Registry for Unified LLM Gateway.
Contains ONLY immutable provider definitions:
- Provider ID
- Base URL
- Authentication strategy (header name, prefix, auth type)
- Discovery endpoint (/models or provider-specific)
- Capability flags
- API format & LiteLLM provider prefix

NEVER store model names in this file. Model discovery is 100% dynamic.
"""
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class ProviderMetadata(BaseModel):
    id: str
    name: str
    aliases: List[str] = Field(default_factory=list)
    base_url: str
    chat_endpoint: str = "/chat/completions"
    models_endpoint: Optional[str] = "/models"
    auth_type: str = "bearer"  # "bearer", "header", "none", "query"
    auth_header_name: str = "Authorization"
    auth_header_prefix: str = "Bearer "
    litellm_prefix: str = "openai/"
    api_format: str = "openai"  # "openai", "gemini", "anthropic", "mistral"
    default_rpm_limit: int = 60
    default_tpm_limit: int = 100_000
    supports_streaming: bool = True
    supports_tools: bool = True
    supports_vision: bool = True
    supports_embeddings: bool = False
    base_priority: int = 50
    extra_headers: Dict[str, str] = Field(default_factory=dict)


# Immutable Metadata Registry for 34+ Providers
PROVIDER_METADATA_REGISTRY: Dict[str, ProviderMetadata] = {
    "google": ProviderMetadata(
        id="google",
        name="Google AI Studio",
        aliases=["google", "google ai studio", "gemini"],
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="gemini/",
        api_format="gemini",
        default_rpm_limit=15,
        default_tpm_limit=1_000_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=95,
    ),
    "groq": ProviderMetadata(
        id="groq",
        name="Groq",
        aliases=["groq"],
        base_url="https://api.groq.com/openai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="groq/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=500_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=95,
    ),
    "cerebras": ProviderMetadata(
        id="cerebras",
        name="Cerebras",
        aliases=["cerebras", "cerebras ai"],
        base_url="https://api.cerebras.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="cerebras/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=500_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=95,
    ),
    "openrouter": ProviderMetadata(
        id="openrouter",
        name="OpenRouter",
        aliases=["openrouter", "open router"],
        base_url="https://openrouter.ai/api/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openrouter/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=500_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=90,
        extra_headers={"HTTP-Referer": "http://localhost:3000", "X-Title": "Unified LLM Gateway"},
    ),
    "nvidia": ProviderMetadata(
        id="nvidia",
        name="NVIDIA NIM",
        aliases=["nvidia", "nvidia nim"],
        base_url="https://integrate.api.nvidia.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=40,
        default_tpm_limit=300_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=90,
    ),
    "mistral": ProviderMetadata(
        id="mistral",
        name="Mistral AI",
        aliases=["mistral", "mistral ai"],
        base_url="https://api.mistral.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="mistral/",
        api_format="mistral",
        default_rpm_limit=30,
        default_tpm_limit=300_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=90,
    ),
    "zhipu": ProviderMetadata(
        id="zhipu",
        name="Zhipu AI",
        aliases=["zhipu", "zhipu ai", "bigmodel"],
        base_url="https://open.bigmodel.cn/api/paas/v4",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=300_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=80,
    ),
    "ollama": ProviderMetadata(
        id="ollama",
        name="Ollama Cloud / Local",
        aliases=["ollama", "ollama cloud"],
        base_url="https://ollama.com/api/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="ollama/",
        api_format="openai",
        default_rpm_limit=120,
        default_tpm_limit=1_000_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=85,
    ),
    "kilo": ProviderMetadata(
        id="kilo",
        name="Kilo Gateway",
        aliases=["kilo", "kilo gateway"],
        base_url="https://api.kilo.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="none",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=200_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=75,
    ),
    "pollinations": ProviderMetadata(
        id="pollinations",
        name="Pollinations AI",
        aliases=["pollinations"],
        base_url="https://text.pollinations.ai/openai",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=200_000,
        supports_vision=True,
        supports_tools=False,
        base_priority=70,
    ),
    "ovh": ProviderMetadata(
        id="ovh",
        name="OVH AI",
        aliases=["ovh", "ovh ai"],
        base_url="https://endpoints.ai.cloud.ovh.net/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="none",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "llm7": ProviderMetadata(
        id="llm7",
        name="LLM7",
        aliases=["llm7"],
        base_url="https://api.llm7.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=300_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=70,
    ),
    "huggingface": ProviderMetadata(
        id="huggingface",
        name="HuggingFace Router",
        aliases=["huggingface", "huggingface router", "hf"],
        base_url="https://api-inference.huggingface.co/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="huggingface/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=200_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=80,
    ),
    "opencode_zen": ProviderMetadata(
        id="opencode_zen",
        name="OpenCode Zen",
        aliases=["opencode zen", "opencode_zen"],
        base_url="https://api.opencodezen.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=300_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=75,
    ),
    "agnes": ProviderMetadata(
        id="agnes",
        name="Agnes AI",
        aliases=["agnes", "agnes ai"],
        base_url="https://api.agnes.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "reka": ProviderMetadata(
        id="reka",
        name="Reka AI",
        aliases=["reka", "reka ai"],
        base_url="https://api.reka.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="header",
        auth_header_name="X-Api-Key",
        auth_header_prefix="",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=200_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=75,
    ),
    "siliconflow": ProviderMetadata(
        id="siliconflow",
        name="SiliconFlow",
        aliases=["siliconflow"],
        base_url="https://api.siliconflow.cn/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=500_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=85,
    ),
    "routeway": ProviderMetadata(
        id="routeway",
        name="Routeway",
        aliases=["routeway"],
        base_url="https://api.routeway.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "bazaarlink": ProviderMetadata(
        id="bazaarlink",
        name="BazaarLink",
        aliases=["bazaarlink"],
        base_url="https://api.bazaarlink.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "aion": ProviderMetadata(
        id="aion",
        name="Aion Labs",
        aliases=["aion", "aion labs"],
        base_url="https://api.aionlabs.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "requesty": ProviderMetadata(
        id="requesty",
        name="Requesty",
        aliases=["requesty"],
        base_url="https://router.requesty.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=300_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=80,
    ),
    "navyai": ProviderMetadata(
        id="navyai",
        name="NavyAI",
        aliases=["navyai", "navy ai"],
        base_url="https://api.navy.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "nararouter": ProviderMetadata(
        id="nararouter",
        name="NaraRouter",
        aliases=["nararouter", "nara router"],
        base_url="https://api.nararouter.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "sea_lion": ProviderMetadata(
        id="sea_lion",
        name="SEA-LION",
        aliases=["sea-lion", "sea_lion", "sealion"],
        base_url="https://api.sea-lion.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=150_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "orcarouter": ProviderMetadata(
        id="orcarouter",
        name="OrcaRouter",
        aliases=["orcarouter", "orca router"],
        base_url="https://api.orcarouter.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "unorouter": ProviderMetadata(
        id="unorouter",
        name="UnoRouter",
        aliases=["unorouter", "uno router"],
        base_url="https://api.unorouter.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "kiro": ProviderMetadata(
        id="kiro",
        name="Kiro",
        aliases=["kiro"],
        base_url="https://api.kiro.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "anyapi": ProviderMetadata(
        id="anyapi",
        name="AnyAPI",
        aliases=["anyapi"],
        base_url="https://api.anyapi.io/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "aihorde": ProviderMetadata(
        id="aihorde",
        name="AI Horde",
        aliases=["ai horde", "aihorde"],
        base_url="https://aihorde.net/api/v2",
        chat_endpoint="/chat/completions",
        models_endpoint="/status/models",
        auth_type="header",
        auth_header_name="apikey",
        auth_header_prefix="",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=30,
        default_tpm_limit=100_000,
        supports_vision=False,
        supports_tools=False,
        base_priority=60,
    ),
    "longcat": ProviderMetadata(
        id="longcat",
        name="LongCat",
        aliases=["longcat"],
        base_url="https://api.longcat.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "sail": ProviderMetadata(
        id="sail",
        name="Sail Research",
        aliases=["sail", "sail research"],
        base_url="https://api.sail.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "b_ai": ProviderMetadata(
        id="b_ai",
        name="B.AI",
        aliases=["b.ai", "b_ai", "bai"],
        base_url="https://api.b.ai/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=45,
        default_tpm_limit=200_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=70,
    ),
    "vercel": ProviderMetadata(
        id="vercel",
        name="Vercel AI",
        aliases=["vercel", "vercel ai"],
        base_url="https://api.vercel.com/v1/ai",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=500_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=80,
    ),
    "deepseek": ProviderMetadata(
        id="deepseek",
        name="DeepSeek",
        aliases=["deepseek", "deepseek ai"],
        base_url="https://api.deepseek.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="deepseek/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=500_000,
        supports_vision=False,
        supports_tools=True,
        base_priority=90,
    ),
    "together": ProviderMetadata(
        id="together",
        name="Together AI",
        aliases=["together", "together ai"],
        base_url="https://api.together.xyz/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="together_ai/",
        api_format="openai",
        default_rpm_limit=60,
        default_tpm_limit=500_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=85,
    ),
    "openai": ProviderMetadata(
        id="openai",
        name="OpenAI",
        aliases=["openai"],
        base_url="https://api.openai.com/v1",
        chat_endpoint="/chat/completions",
        models_endpoint="/models",
        auth_type="bearer",
        auth_header_name="Authorization",
        auth_header_prefix="Bearer ",
        litellm_prefix="openai/",
        api_format="openai",
        default_rpm_limit=100,
        default_tpm_limit=1_000_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=95,
    ),
    "anthropic": ProviderMetadata(
        id="anthropic",
        name="Anthropic",
        aliases=["anthropic", "claude"],
        base_url="https://api.anthropic.com/v1",
        chat_endpoint="/messages",
        models_endpoint="/models",
        auth_type="header",
        auth_header_name="x-api-key",
        auth_header_prefix="",
        litellm_prefix="anthropic/",
        api_format="anthropic",
        default_rpm_limit=50,
        default_tpm_limit=500_000,
        supports_vision=True,
        supports_tools=True,
        base_priority=95,
        extra_headers={"anthropic-version": "2023-06-01"},
    ),
}


def find_provider_metadata(name_or_id: str) -> Optional[ProviderMetadata]:
    """Finds provider metadata by ID or alias (case-insensitive)."""
    norm = name_or_id.lower().strip()
    if norm in PROVIDER_METADATA_REGISTRY:
        return PROVIDER_METADATA_REGISTRY[norm]

    for spec in PROVIDER_METADATA_REGISTRY.values():
        if norm == spec.id.lower() or norm == spec.name.lower():
            return spec
        if any(norm == a.lower() for a in spec.aliases):
            return spec

    # Partial match
    for spec in PROVIDER_METADATA_REGISTRY.values():
        if norm in spec.id.lower() or norm in spec.name.lower():
            return spec
    return None
