"""
Sample Client demonstrating how to use the Unified Multi-Provider LLM Gateway.
Works with the standard OpenAI Python SDK, cURL, or any OpenAI-compatible client.
"""
import os
import sys
from pathlib import Path
from openai import OpenAI
import httpx

# Ensure Windows terminal outputs UTF-8 properly (e.g. for emojis/special characters)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Read the unified key generated by the gateway
KEY_FILE = Path(__file__).resolve().parent / "unified_key.txt"
UNIFIED_KEY = ""
if KEY_FILE.exists():
    UNIFIED_KEY = KEY_FILE.read_text(encoding="utf-8").strip()

if not UNIFIED_KEY:
    UNIFIED_KEY = os.environ.get("UNIFIED_API_KEY", "sk-unified-gateway-key")

GATEWAY_BASE_URL = "http://127.0.0.1:8000/v1"


def test_openai_sdk():
    print("\n" + "=" * 60)
    print(" 1. Testing Standard OpenAI SDK with model='auto'")
    print("=" * 60)

    client = OpenAI(
        base_url=GATEWAY_BASE_URL,
        api_key=UNIFIED_KEY
    )

    try:
        response = client.chat.completions.create(
            model="auto",  # Dynamic auto-routing across 32 providers
            messages=[
                {"role": "system", "content": "You are a helpful AI assistant."},
                {"role": "user", "content": "Explain quantum computing in one sentence."}
            ],
            temperature=0.7,
        )
        print("\n>> AI Response:")
        print(response.choices[0].message.content)
        print(f"\n>> Model used: {response.model}")
    except Exception as e:
        print(f"[!] Error: {e}")


def test_streaming():
    print("\n" + "=" * 60)
    print(" 2. Testing Streaming Response with model='auto'")
    print("=" * 60)

    client = OpenAI(
        base_url=GATEWAY_BASE_URL,
        api_key=UNIFIED_KEY
    )

    try:
        stream = client.chat.completions.create(
            model="auto",
            messages=[
                {"role": "user", "content": "Count from 1 to 5 with a short cheering word for each number."}
            ],
            stream=True
        )
        print("\n>> Stream Output: ", end="", flush=True)
        for chunk in stream:
            if chunk.choices and chunk.choices[0].delta and chunk.choices[0].delta.content:
                print(chunk.choices[0].delta.content, end="", flush=True)
        print("\n")
    except Exception as e:
        print(f"[!] Stream Error: {e}")


def test_models_and_stats():
    print("\n" + "=" * 60)
    print(" 3. Inspecting Available Models and Real-Time Quota Stats")
    print("=" * 60)

    headers = {"Authorization": f"Bearer {UNIFIED_KEY}"}
    
    # Models
    try:
        resp = httpx.get(f"{GATEWAY_BASE_URL}/models", headers=headers)
        if resp.status_code == 200:
            models = resp.json().get("data", [])
            print(f"[*] Discovered {len(models)} available models across providers.")
            print(f"[*] First 8 models: {[m['id'] for m in models[:8]]}")
    except Exception as e:
        print(f"[!] Models endpoint error: {e}")

    # Stats
    try:
        stats_url = f"{GATEWAY_BASE_URL.rsplit('/v1', 1)[0]}/stats"
        resp = httpx.get(stats_url, headers=headers)
        if resp.status_code == 200:
            stats = resp.json()
            print(f"[*] Quota Tracker Stats:")
            print(f"    - Total Monitored Models: {stats.get('total_monitored_models')}")
            print(f"    - Healthy Models:         {stats.get('healthy')}")
            print(f"    - Cooldown Models:        {stats.get('cooldown')}")
            print(f"    - Tokens Used Today:      {stats.get('total_tokens_used_today')}")
    except Exception as e:
        print(f"[!] Stats error: {e}")


if __name__ == "__main__":
    print(f"Using Gateway Unified Key: {UNIFIED_KEY}")
    test_openai_sdk()
    test_streaming()
    test_models_and_stats()
